language: go

go:
    - "1.8.3"

sudo: false

branches:
    only:
        - master

before_script:
    - git clone -b 'v0.24' --single-branch --depth 1 https://github.com/spf13/hugo.git $GOPATH/src/github.com/spf13/hugo
    - go get -u -v github.com/spf13/hugo

script:
    - hugo version
    - hugo

before_deploy:
    - echo 'indragunawan.id' > public/CNAME

deploy:
    provider: pages
    local_dir: public
    skip_cleanup: true
    github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    fqdn: indragunawan.id
    on:
        branch: master
